### ISSUE TITLE
When using demoapps, building rumprun fails.

### ISSUE THREAD

**Issue by pittma** [SEL4PROJ/rumprun#2]
Hi all!

I'm not sure if this is the right place to land this issue, so if not, please let me know.

When running `make`, I've been landing at a type error, specifically [here](https://github.com/SEL4PROJ/rumprun/blob/b223ed741d47d93d72ec95a295eb8905f7af7b5c/platform/sel4/pci/rumppci.c#L225).   Looking at the history of this file, I see [a commit (`b223ed7`) that changed only this line](https://github.com/SEL4PROJ/rumprun/commit/b223ed741d47d93d72ec95a295eb8905f7af7b5c) from 11 days ago.  When I discard this commit, `make` exits successfully, and all is well.

Here's my system's config:
```
$ uname -a
Linux dpitts-thinkpad 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by kent-mcleod** [comment]
Hi!

I believe this is likely due to the corresponding change to the libsel4 api that deprecated `seL4_CapData_Badge_new`.  What commit hash/version of the seL4 kernel are you using?

**Comment by pittma** [comment]
To be completely honest, I've cargo-culted through a fair amount of this today :smile:

I'm using the version that demoapps pulls via the repo tool, I believe.
```
$ git remote -v
seL4    https://github.com/seL4/seL4 (fetch)
seL4    https://github.com/seL4/seL4 (push)
$ git describe
API-master-01-03--release-2014-08-10-1862-g18db530
```

**Comment by kent-mcleod** [comment]
Disregard what I initially wrote below.  This rumprun repo has gotten out of sync with the core seL4 github repositories.  Because of a internally failing seL4 verification regression test, the core seL4 repos haven't been updated in a few days.  But because the internal rumprun regression tests are passing this one got pushed out (With newer changes that depends on changes that haven't been pushed out for other repos yet).  Until the github repos get up dated, discarding the last 3 commits is likely the easiest work around.

Thanks for bringing this to our attention!

~~So what seems to have happened is that the api change in libsel4 broke a function definition in libsel4vka.  Normally our internal regression would prevent the github repos from being updated until this was fixed, but the sel4test project doesn't use vka_mint_object, thus not triggering the error condition.  I'll let you know when the updated version of the libraries get pushed out which will fix this compilation error.~~

~~As for the problem of preventing this from happening in the future, we probably need to start versioning the demoapps application against released versions of the sel4 libraries which will reduce the chance of these breakages from happening.~~

**Comment by kent-mcleod** [comment]
Ok it should be fixed now.

**Comment by pittma** [comment]
Hi @kent-mcleod, and sorry for the delay on this.  I tried again this morning with a fresh fetch and everything worked as expected.  Thanks for your help!
